version: "3.7"
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    networks:
      - net
      - private

  user-app:
    build: ./user-app
    expose:
      - 3000
    networks:
      - private

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      # - 9411:9411
    volumes:
      - ./jaeger:/etc/jaeger/configs/
      - jaeger_data:/var/lib/jaeger
    environment:
      - JAEGER_DISABLED=true
    command:
      - --query.ui-config=/etc/jaeger/configs/config.json
    networks:
      - net
      - private

  # zipkin:
  #   image: openzipkin/zipkin
  #   ports:
  #     - "9411:9411"
  #   networks:
  #     - net

volumes:
  jaeger_data:

networks:
  net:
    driver: bridge
  private:
